### ISSUE TITLE
Flytte repo fra private til public

### ISSUE THREAD

**Issue by MikAoJk** [navikt/syfooppfolgingsplanservice#218]
Hei!
Lurte på om det var noe spesiell grunn til at repoet er private.
https://github.com/navikt/offentlig

**Comment by luantr** [comment]
@MikAoJk Det er nå endret. Det var ingen grunn til at repoet skal være private. Takk for info :)

**Comment by MikAoJk** [comment]
Supert!
Bra jobba :rocket:
