### ISSUE TITLE
Migrer fra `dkif` til `digdir-krr-proxy`

### ISSUE THREAD

**Issue by ThomasKasene** [navikt/syfooppfolgingsplanservice#379]
`dkif` skal dø på sikt, og det er best om dere får flyttet dere over på `digdir-krr-proxy` isteden. Det finnes en [migreringsguide](https://github.com/navikt/digdir-krr/wiki/dkif-(REST)-%E2%86%92-digdir-krr-proxy-(REST)) som dere kan følge. Ta kontakt i [#team-rocket](https://nav-it.slack.com/archives/C01BXHWPLR4) på Slack dersom dere har behov for hjelp 😃

**Comment by torchr89** [comment]
Løst i følgende PR/commit: https://github.com/navikt/syfooppfolgingsplanservice/pull/382
